%这个例子展示excel的基本读取操作，读取的excel文件必须与此程序同文件夹
%而且文件必须不能被其他程序占用
clear
name='ex1.xlsx';
range=['A2:B1557'];
A=xlsread(name,range);
load('data0.mat')
%下面展示基本的数据统计技巧，包括数据的均值和方差等
t=mean(A);%计算每一列的平均值
s=var(A);%计算数据的方差，如果后面加上参数1表示计算时除以N